version: '3'

services:
  # consul client agents
  consul-client-1: &consul-agent
    build: ./agent
    networks:
      - consul-demo
    command: "agent -node=consul-client-1 -retry-join consul-server-bootstrap -client 0.0.0.0 --config-file /etc/consul.d/default.json"

  # consul server agents
  consul-server-bootstrap:
    build: ./server
    networks:
      - consul-demo
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: sh -c "consul agent -server -node=consul-server-bootstrap -bootstrap-expect 1 -client 0.0.0.0 --config-file /etc/consul.d/default.json"
  
  # consul-esm
  consul-esm:
    container_name: consul-esm
    hostname: consul-esm
    image: 'hashicorp/consul-esm'
    restart: always
    networks:
      - consul-demo
    environment:
      CONSUL_HTTP_ADDR: "http://consul-server-bootstrap:8500"

  # dashboard app
  dashboard:
    container_name: dashboard
    hostname: dashboard
    image: 'hashicorp/dashboard-service:0.0.4'
    restart: always
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      COUNTING_SERVICE_URL: 'http://counting-service:9001'
    depends_on:
      - counting-service
    networks:
      - consul-demo

  # counting service app
  counting-service:
    container_name: counting-service
    hostname: counting-service
    image: 'hashicorp/counting-service:0.0.2'
    restart: always
    ports:
      - '9001:9001'
    environment:
      PORT: 9001
    networks:
      - consul-demo
  

  
networks:
  consul-demo: